# Generated by Django 3.2.8 on 2021-11-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='img',
            field=models.ImageField(default='avatar.png', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='img',
            field=models.ImageField(default='avatar.png', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='lender',
            name='img',
            field=models.ImageField(default='avatar.png', upload_to='pics'),
        ),
    ]
