# Generated by Django 3.2.8 on 2021-11-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211103_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='img',
            field=models.ImageField(default='avatar.png', upload_to='pics/'),
        ),
    ]
