# Generated by Django 3.2.8 on 2021-10-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_account_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='credit',
            new_name='loan',
        ),
    ]
