# Generated by Django 3.2.8 on 2021-10-16 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_alter_invest_lender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('totalamount', models.IntegerField(blank=True, default=0, null=True)),
                ('landbuyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landQTY', models.IntegerField(blank=True, default=0, null=True)),
                ('rsdag', models.TextField(blank=True, null=True)),
                ('perDprice', models.IntegerField(blank=True, default=0, null=True)),
                ('mouja', models.TextField(blank=True, null=True)),
                ('landowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.landowner')),
            ],
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('advance', models.IntegerField(blank=True, default=0, null=True)),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.land')),
            ],
        ),
    ]
