# Generated by Django 3.2.8 on 2021-10-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_advance_land_landowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landowner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='landowner',
            name='totalamount',
        ),
        migrations.AddField(
            model_name='landowner',
            name='Landownername',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
