# Generated by Django 3.2.8 on 2021-10-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211016_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='mouja',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='land',
            name='rsdag',
            field=models.CharField(max_length=50),
        ),
    ]
