# Generated by Django 3.2.8 on 2021-10-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211023_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
