# Generated by Django 3.2.8 on 2021-10-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_landowner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
